### ISSUE TITLE
No implementation 

### ISSUE THREAD

**Issue by Nasirkc** [eterkit/flutter-packages#2]
E/flutter (20281): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method detectEdges on channel eterkit.com/edge_detector)   
E/flutter (20281): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)

**Comment by marcsanny** [comment]
> E/flutter (20281): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method detectEdges on channel eterkit.com/edge_detector)
> E/flutter (20281): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)

Hello, probably you just have to restart the application from scratch, but...
the plugin is discontinued and unlisted as I'm working on a way better version of it - it will depend on open-cv. I'll do my best to publish it asap. Thanks for understanding. I will mark the issue as closed as edge_detector plugin is no longer available
