### ISSUE TITLE
Descriptive & short bug title

### ISSUE THREAD

**Issue by zhoudajun-ola** [eterkit/flutter-packages#5]
**permission_guard** 

**Description**
PermissionGuardOptions `copyWith`  method dont copy `descriptionBuilder` and `actionBuilder`.

**Comment by marcsanny** [comment]
Thanks, will have a look at it this week probably

**Comment by marcsanny** [comment]
Resolved in: https://github.com/eterkit/flutter-packages/commit/12b0fafe948224ebf062cf1a6c3cd20bf9df4fa6
